---
- name: Copy markdown files to deploys home directory on db server
  hosts: db
  become: true

  tasks:
    - name: Copy all markdown files to deploys home directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/deploy/"
        owner: deploy
        group: deploy
        mode: '0644'
      with_fileglob:
        - "files/*.md"
