---
- name: Secure deploy sudo privileges
  hosts: all
  become: true

  tasks:
    - name: Gather shadow entries
      ansible.builtin.getent:
        database: shadow

    - name: Ensure deploy user has password if not set
      ansible.builtin.user:
        name: deploy
        password: "{{ 'hunter12' | password_hash('sha512') }}"
      when: ansible_facts.getent_shadow.deploy[0] in ['', '!', '*']

    - name: Remove passwordless sudo (NOPASSWD) and enforce password requirement
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/deploy
        regexp: "^%?deploy.*NOPASSWD: ALL"
        line: "deploy ALL=(ALL) ALL"
        validate: "visudo -cf %s"  # Validates the file
